# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bj9IXTZ_QlFOcF_eykvzStaXClJEEjgN
"""

# Function to classify temperature
def classify_temperature(temp):
    if temp < 18:
        return "Cold"
    elif temp <= 28:
        return "Normal"
    else:
        return "Hot"


# Function to calculate statistics
def calculate_statistics(readings):
    average = sum(readings) / len(readings)
    highest = max(readings)
    lowest = min(readings)

    return average, highest, lowest


# Function to count conditions
def count_conditions(readings):
    counts = {
        "Hot": 0,
        "Normal": 0,
        "Cold": 0
    }

    for temp in readings:
        condition = classify_temperature(temp)
        counts[condition] += 1

    return counts


# Function to determine actions
def determine_actions(counts):
    actions = []

    if counts["Hot"] > 0:
        actions.append("Fan ON")

    if counts["Cold"] > 0:
        actions.append("Heater ON")

    if not actions:
        actions.append("No action required")

    return actions


# Function to display report
def display_report(readings, average, highest, lowest, counts, actions):

    print("\n===== Temperature Summary =====")

    print(f"Average Temperature = {average:.2f}")
    print(f"Highest Temperature = {highest}")
    print(f"Lowest Temperature = {lowest}")

    print("\nCondition Count")
    print(f"Hot = {counts['Hot']}")
    print(f"Normal = {counts['Normal']}")
    print(f"Cold = {counts['Cold']}")

    print("\nSuggested Action")
    for action in actions:
        print(action)


# Main function
def main():

    readings = []

    # Input number of readings
    n = int(input("Enter number of readings: "))

    # Input temperature values
    for i in range(n):
        temp = float(input(f"Enter temperature {i+1}: "))
        readings.append(temp)

    # Process data
    average, highest, lowest = calculate_statistics(readings)

    counts = count_conditions(readings)

    actions = determine_actions(counts)

    # Display report
    display_report(readings, average, highest, lowest, counts, actions)


# Run program
if __name__ == "__main__":
    main()